kind: pipeline
type: docker
name: default

steps:
    - name: testspace
      image: buildpack-deps:18.04-scm
      commands:
        - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C /usr/local/bin
        - testspace config url samples.testspace.com
        - testspace results.xml
      environment:
        TESTSPACE_TOKEN:
          from_secret: testspace_token
      when:
        status: [ failure, success ]
     